empty_tuple=()
print("\n","Here is the empty tuple: ",empty_tuple)
sisters_tuple=('Leslie','Paulina')
print("\n","Here is the sisters tuple: ",sisters_tuple)
brothers_tuple=('Juan','Jose')
print("\n","Here is the brothers tuple: ",brothers_tuple)
brothers_tuple=sisters_tuple+brothers_tuple
print("\n","Here are the tuples joinned: ",brothers_tuple)
lenght=len(brothers_tuple)
print("\n","I have ",lenght," siblings")
lista=list(brothers_tuple)
lista.insert(0,'Gabriela')
lista.insert(0,'Victor')
family_members=tuple(lista)
print("\n","Here is the list with the names of my parents: ",family_members)